const entries: Entry[] = [
  {
    id: 1,
    type: 'warmup',
    name: 'Jogging',
    time: 120,
    isCurrent: true,
    isNext: false,
  },
  {
    id: 2,
    type: 'warmup',
    name: 'Arm circles',
    time: 60,
    isCurrent: false,
    isNext: true,
  },
  {
    id: 3,
    type: 'warmup',
    name: 'Leg swings',
    time: 60,
    isCurrent: false,
    isNext: false,
  },
  {
    id: 4,
    type: 'exercise',
    name: 'Bodyweight Squats',
    reps: 15,
    isCurrent: false,
    isNext: false,
  },
  {
    id: 5,
    type: 'rest',
    name: '30 secs rest',
    time: 30,
    isCurrent: false,
    isNext: false,
  },
  {
    id: 6,
    type: 'exercise',
    name: 'Push-Ups',
    reps: 10,
    isCurrent: false,
    isNext: false,
  },
  {
    id: 7,
    type: 'rest',
    name: '30 secs rest',
    time: 30,
    isCurrent: false,
    isNext: false,
  },
  {
    id: 8,
    type: 'exercise',
    name: 'Lunges',
    reps: 20,
    notes: '10 reps each leg',
    isCurrent: false,
    isNext: false,
  },
  {
    id: 9,
    type: 'rest',
    name: '30 secs rest',
    time: 30,
    isCurrent: false,
    isNext: false,
  },
  {
    id: 10,
    type: 'exercise',
    name: 'Dumbbell Bent-Over Rows',
    reps: 12,
    isCurrent: false,
    isNext: false,
  },
  {
    id: 11,
    type: 'rest',
    name: '30 secs rest',
    time: 30,
    isCurrent: false,
    isNext: false,
  },
  {
    id: 12,
    type: 'exercise',
    name: 'Plank',
    time: 30,
    isCurrent: false,
    isNext: false,
  },
  {
    id: 13,
    type: 'rest',
    name: '30 secs rest',
    time: 30,
    isCurrent: false,
    isNext: false,
  },
  {
    id: 14,
    type: 'exercise',
    name: 'Russian Twists',
    reps: 30,
    notes: '15 reps each side',
    isCurrent: false,
    isNext: false,
  },
  {
    id: 15,
    type: 'cooldown',
    name: 'Cooldown Static Stretches',
    time: 60,
    isCurrent: false,
    isNext: false,
  },
];

export default entries;
